{"name": "Try to delete pet by invalid ID", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected error message: b'{\"code\":400,\"message\":\"Input error: couldn\\'t convert `2.5` to type `class java.lang.Long`\"}' instead of Invalid pet value", "trace": "self = <tests_project.tests.test_delete_pet.TestDeletePet object at 0x7f8321dcd940>\ninvalid_id = '2.5'\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.title(\"Try to delete pet by invalid ID\")\n    @pytest.mark.parametrize(\"invalid_id\", invalid_ids)\n    def test_delete_pet_with_invalid_id(self, invalid_id):\n        response = MyRequests.delete(\n            f\"/pet/{invalid_id}\"\n        )\n    \n        Assertions.assert_code_status(response, 400)\n>       Assertions.assert_error_message(response, 'Invalid pet value')\n\ntests/test_delete_pet.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [400]>, expected_error_message = 'Invalid pet value'\n\n    @staticmethod\n    @allure.step(\"Check the server returns error message '{expected_error_message}'\")\n    def assert_error_message(response: Response, expected_error_message):\n>       assert response.content.decode() == expected_error_message, \\\n            f\"Unexpected error message: {response.content} instead of {expected_error_message}\"\nE       AssertionError: Unexpected error message: b'{\"code\":400,\"message\":\"Input error: couldn\\'t convert `2.5` to type `class java.lang.Long`\"}' instead of Invalid pet value\n\nlib/assertions.py:46: AssertionError"}, "steps": [{"name": "DELETE request to URL '/pet/2.5'", "status": "passed", "start": 1744662020757, "stop": 1744662020767}, {"name": "Check status code is 400", "status": "passed", "parameters": [{"name": "response", "value": "<Response [400]>"}, {"name": "expected_status_code", "value": "400"}], "start": 1744662020767, "stop": 1744662020767}, {"name": "Check the server returns error message ''Invalid pet value''", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected error message: b'{\"code\":400,\"message\":\"Input error: couldn\\'t convert `2.5` to type `class java.lang.Long`\"}' instead of Invalid pet value\n", "trace": "  File \"/usr/local/lib/python3.13/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/tests_project/lib/assertions.py\", line 46, in assert_error_message\n    assert response.content.decode() == expected_error_message, \\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "parameters": [{"name": "response", "value": "<Response [400]>"}, {"name": "expected_error_message", "value": "'Invalid pet value'"}], "start": 1744662020767, "stop": 1744662020767}], "parameters": [{"name": "invalid_id", "value": "'2.5'"}], "start": 1744662020757, "stop": 1744662020768, "uuid": "5fe4f75a-0f50-4ccf-8d3e-9f9ea9230704", "historyId": "cd9f52f428dcf2cf524f466938420ea1", "testCaseId": "fbfe7538c8b7bc26d6f66d08706f29d4", "fullName": "tests.test_delete_pet.TestDeletePet#test_delete_pet_with_invalid_id", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_delete_pet"}, {"name": "subSuite", "value": "TestDeletePet"}, {"name": "host", "value": "4c2631702ffc"}, {"name": "thread", "value": "7-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_delete_pet"}]}