{"name": "Try to update pet with invalid name True", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected status code! Expected: 405. Actual: 200", "trace": "self = <tests.test_update_pet.TestUpdatePet object at 0x106306c50>, invalid_name = True\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.title(\"Try to update pet with invalid name {invalid_name}\")\n    @pytest.mark.parametrize(\"invalid_name\", invalid_names)\n    def test_update_pet_with_invalid_name(self, invalid_name):\n        pet = self.create_pet()\n        pet_id = self.get_json_value(pet, \"id\")\n        data = {\n            \"id\": pet_id,\n            \"name\": invalid_name,\n            \"photoUrls\": [\"string\"]\n        }\n    \n        response = MyRequests.put(\n            \"/pet/\",\n            data)\n    \n>       Assertions.assert_code_status(response, 405)\n\ntests/test_update_pet.py:130: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [200]>, expected_status_code = 405\n\n    @staticmethod\n    @allure.step(\"Check status code is {expected_status_code}\")\n    def assert_code_status(response: Response, expected_status_code):\n>       assert response.status_code == expected_status_code, \\\n            f\"Unexpected status code! Expected: {expected_status_code}. Actual: {response.status_code}\"\nE       AssertionError: Unexpected status code! Expected: 405. Actual: 200\n\nlib/assertions.py:30: AssertionError"}, "steps": [{"name": "Create pet", "status": "passed", "steps": [{"name": "Prepare pet creation data", "status": "passed", "start": 1744657923485, "stop": 1744657923485}, {"name": "POST request to URL '/pet/'", "status": "passed", "start": 1744657923485, "stop": 1744657923492}], "start": 1744657923485, "stop": 1744657923492}, {"name": "PUT request to URL '/pet/'", "status": "passed", "start": 1744657923492, "stop": 1744657923497}, {"name": "Check status code is 405", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected status code! Expected: 405. Actual: 200\n", "trace": "  File \"/Users/miowch/.pyenv/versions/n26_nastia_kuzina/lib/python3.10/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/Users/miowch/Documents/GitHub/nastia-kuzina/Task3/api-e2e-tests/lib/assertions.py\", line 30, in assert_code_status\n    assert response.status_code == expected_status_code, \\\n"}, "parameters": [{"name": "response", "value": "<Response [200]>"}, {"name": "expected_status_code", "value": "405"}], "start": 1744657923497, "stop": 1744657923498}], "parameters": [{"name": "invalid_name", "value": "True"}], "start": 1744657923485, "stop": 1744657923498, "uuid": "1c318ee6-b1ee-4baa-877b-713bb2017695", "historyId": "372a30af3a4244a0030cd8afa9473488", "testCaseId": "bce2133eaaa071b286297e7bd3adaa97", "fullName": "tests.test_update_pet.TestUpdatePet#test_update_pet_with_invalid_name", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_update_pet"}, {"name": "subSuite", "value": "TestUpdatePet"}, {"name": "host", "value": "iMac.local"}, {"name": "thread", "value": "58784-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_update_pet"}]}