{"name": "Try to update pet with invalid photoUrl", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected status code! Expected: 405. Actual: 200", "trace": "self = <tests_project.tests.test_update_pet.TestUpdatePet object at 0x7f8321dc72f0>\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.title(\"Try to update pet with invalid photoUrl\")\n    def test_update_pet_with_invalid_photoUrls(self):\n        pet = self.create_pet()\n        pet_id = self.get_json_value(pet, \"id\")\n        data = {\n            \"id\": pet_id,\n            \"name\": self.fake.first_name(),\n            \"photoUrls\": (\"string\", 2, 7)\n        }\n    \n        response = MyRequests.put(\n            \"/pet/\",\n            data)\n    \n>       Assertions.assert_code_status(response, 405)\n\ntests/test_update_pet.py:165: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [200]>, expected_status_code = 405\n\n    @staticmethod\n    @allure.step(\"Check status code is {expected_status_code}\")\n    def assert_code_status(response: Response, expected_status_code):\n>       assert response.status_code == expected_status_code, \\\n            f\"Unexpected status code! Expected: {expected_status_code}. Actual: {response.status_code}\"\nE       AssertionError: Unexpected status code! Expected: 405. Actual: 200\n\nlib/assertions.py:30: AssertionError"}, "steps": [{"name": "Create pet", "status": "passed", "steps": [{"name": "Prepare pet creation data", "status": "passed", "start": 1744662021294, "stop": 1744662021294}, {"name": "POST request to URL '/pet/'", "status": "passed", "start": 1744662021294, "stop": 1744662021302}], "start": 1744662021294, "stop": 1744662021302}, {"name": "PUT request to URL '/pet/'", "status": "passed", "start": 1744662021302, "stop": 1744662021311}, {"name": "Check status code is 405", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected status code! Expected: 405. Actual: 200\n", "trace": "  File \"/usr/local/lib/python3.13/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/tests_project/lib/assertions.py\", line 30, in assert_code_status\n    assert response.status_code == expected_status_code, \\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "parameters": [{"name": "response", "value": "<Response [200]>"}, {"name": "expected_status_code", "value": "405"}], "start": 1744662021311, "stop": 1744662021311}], "start": 1744662021293, "stop": 1744662021312, "uuid": "c4427118-7eda-4d6d-95ef-dc39c302355b", "historyId": "eadb6b590f472aa89b03e5d6844fbabc", "testCaseId": "eadb6b590f472aa89b03e5d6844fbabc", "fullName": "tests.test_update_pet.TestUpdatePet#test_update_pet_with_invalid_photoUrls", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_update_pet"}, {"name": "subSuite", "value": "TestUpdatePet"}, {"name": "host", "value": "4c2631702ffc"}, {"name": "thread", "value": "7-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_update_pet"}]}