{"name": "Try to create pet with invalid ID", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected status code! Expected: 405. Actual: 500", "trace": "self = <tests.test_add_pet.TestAddPet object at 0x106232200>, invalid_id = 'two'\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.title(\"Try to create pet with invalid ID\")\n    @pytest.mark.parametrize(\"invalid_id\", invalid_ids)\n    def test_add_pet_with_invalid_id(self, invalid_id):\n        data = {\n            \"id\": invalid_id,\n            \"name\": self.fake.first_name(),\n            \"photoUrls\": [\"string\"]\n        }\n    \n        response = MyRequests.post(\n            \"/pet/\",\n            data)\n    \n>       Assertions.assert_code_status(response, 405)\n\ntests/test_add_pet.py:158: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [500]>, expected_status_code = 405\n\n    @staticmethod\n    @allure.step(\"Check status code is {expected_status_code}\")\n    def assert_code_status(response: Response, expected_status_code):\n>       assert response.status_code == expected_status_code, \\\n            f\"Unexpected status code! Expected: {expected_status_code}. Actual: {response.status_code}\"\nE       AssertionError: Unexpected status code! Expected: 405. Actual: 500\n\nlib/assertions.py:30: AssertionError"}, "steps": [{"name": "POST request to URL '/pet/'", "status": "passed", "start": 1744657922962, "stop": 1744657922970}, {"name": "Check status code is 405", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected status code! Expected: 405. Actual: 500\n", "trace": "  File \"/Users/miowch/.pyenv/versions/n26_nastia_kuzina/lib/python3.10/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/Users/miowch/Documents/GitHub/nastia-kuzina/Task3/api-e2e-tests/lib/assertions.py\", line 30, in assert_code_status\n    assert response.status_code == expected_status_code, \\\n"}, "parameters": [{"name": "response", "value": "<Response [500]>"}, {"name": "expected_status_code", "value": "405"}], "start": 1744657922970, "stop": 1744657922970}], "parameters": [{"name": "invalid_id", "value": "'two'"}], "start": 1744657922962, "stop": 1744657922970, "uuid": "21637c8e-5811-422b-945b-514cc19a6e10", "historyId": "f59b3ee1bf45619278d419ff519af14c", "testCaseId": "f44260dc902a96eebb3ac4f990b02d72", "fullName": "tests.test_add_pet.TestAddPet#test_add_pet_with_invalid_id", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_add_pet"}, {"name": "subSuite", "value": "TestAddPet"}, {"name": "host", "value": "iMac.local"}, {"name": "thread", "value": "58784-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_add_pet"}]}