{"name": "Try to delete pet by invalid ID", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected error message: b'{\"code\":400,\"message\":\"Input error: couldn\\'t convert `False` to type `class java.lang.Long`\"}' instead of Invalid pet value", "trace": "self = <tests.test_delete_pet.TestDeletePet object at 0x1062c7af0>, invalid_id = False\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.title(\"Try to delete pet by invalid ID\")\n    @pytest.mark.parametrize(\"invalid_id\", invalid_ids)\n    def test_delete_pet_with_invalid_id(self, invalid_id):\n        response = MyRequests.delete(\n            f\"/pet/{invalid_id}\"\n        )\n    \n        Assertions.assert_code_status(response, 400)\n>       Assertions.assert_error_message(response, 'Invalid pet value')\n\ntests/test_delete_pet.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [400]>, expected_error_message = 'Invalid pet value'\n\n    @staticmethod\n    @allure.step(\"Check the server returns error message '{expected_error_message}'\")\n    def assert_error_message(response: Response, expected_error_message):\n>       assert response.content.decode() == expected_error_message, \\\n            f\"Unexpected error message: {response.content} instead of {expected_error_message}\"\nE       AssertionError: Unexpected error message: b'{\"code\":400,\"message\":\"Input error: couldn\\'t convert `False` to type `class java.lang.Long`\"}' instead of Invalid pet value\n\nlib/assertions.py:46: AssertionError"}, "steps": [{"name": "DELETE request to URL '/pet/False'", "status": "passed", "start": 1744657923086, "stop": 1744657923094}, {"name": "Check status code is 400", "status": "passed", "parameters": [{"name": "response", "value": "<Response [400]>"}, {"name": "expected_status_code", "value": "400"}], "start": 1744657923094, "stop": 1744657923094}, {"name": "Check the server returns error message ''Invalid pet value''", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected error message: b'{\"code\":400,\"message\":\"Input error: couldn\\'t convert `False` to type `class java.lang.Long`\"}' instead of Invalid pet value\n", "trace": "  File \"/Users/miowch/.pyenv/versions/n26_nastia_kuzina/lib/python3.10/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/Users/miowch/Documents/GitHub/nastia-kuzina/Task3/api-e2e-tests/lib/assertions.py\", line 46, in assert_error_message\n    assert response.content.decode() == expected_error_message, \\\n"}, "parameters": [{"name": "response", "value": "<Response [400]>"}, {"name": "expected_error_message", "value": "'Invalid pet value'"}], "start": 1744657923094, "stop": 1744657923094}], "parameters": [{"name": "invalid_id", "value": "False"}], "start": 1744657923086, "stop": 1744657923094, "uuid": "e0f8568a-237e-4fba-9fe7-4c1f9f42ccfa", "historyId": "6f4eacab82aea011980014c9d6b9377d", "testCaseId": "fbfe7538c8b7bc26d6f66d08706f29d4", "fullName": "tests.test_delete_pet.TestDeletePet#test_delete_pet_with_invalid_id", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_delete_pet"}, {"name": "subSuite", "value": "TestDeletePet"}, {"name": "host", "value": "iMac.local"}, {"name": "thread", "value": "58784-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_delete_pet"}]}