{"name": "Get pet by invalid ID", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected error message: b'{\"code\":400,\"message\":\"Input error: couldn\\'t convert `one` to type `class java.lang.Long`\"}' instead of Invalid ID supplied", "trace": "self = <tests_project.tests.test_get_pet.TestGetPet object at 0x7f8321bd5450>\n\n    @allure.severity(allure.severity_level.NORMAL)\n    @allure.title(\"Get pet by invalid ID\")\n    def test_get_pet_by_invalid_id(self):\n        response = MyRequests.get(f\"/pet/one\")\n    \n        Assertions.assert_code_status(response, 400)\n>       Assertions.assert_error_message(response, \"Invalid ID supplied\")\n\ntests/test_get_pet.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [400]>, expected_error_message = 'Invalid ID supplied'\n\n    @staticmethod\n    @allure.step(\"Check the server returns error message '{expected_error_message}'\")\n    def assert_error_message(response: Response, expected_error_message):\n>       assert response.content.decode() == expected_error_message, \\\n            f\"Unexpected error message: {response.content} instead of {expected_error_message}\"\nE       AssertionError: Unexpected error message: b'{\"code\":400,\"message\":\"Input error: couldn\\'t convert `one` to type `class java.lang.Long`\"}' instead of Invalid ID supplied\n\nlib/assertions.py:46: AssertionError"}, "steps": [{"name": "GET request to URL '/pet/one'", "status": "passed", "start": 1744662020978, "stop": 1744662020988}, {"name": "Check status code is 400", "status": "passed", "parameters": [{"name": "response", "value": "<Response [400]>"}, {"name": "expected_status_code", "value": "400"}], "start": 1744662020988, "stop": 1744662020988}, {"name": "Check the server returns error message ''Invalid ID supplied''", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected error message: b'{\"code\":400,\"message\":\"Input error: couldn\\'t convert `one` to type `class java.lang.Long`\"}' instead of Invalid ID supplied\n", "trace": "  File \"/usr/local/lib/python3.13/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/tests_project/lib/assertions.py\", line 46, in assert_error_message\n    assert response.content.decode() == expected_error_message, \\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "parameters": [{"name": "response", "value": "<Response [400]>"}, {"name": "expected_error_message", "value": "'Invalid ID supplied'"}], "start": 1744662020988, "stop": 1744662020988}], "start": 1744662020978, "stop": 1744662020989, "uuid": "7a599ffa-d8a4-45a0-a68e-5a4b772988f6", "historyId": "2080646c88aeeeacc5684328842465bc", "testCaseId": "2080646c88aeeeacc5684328842465bc", "fullName": "tests.test_get_pet.TestGetPet#test_get_pet_by_invalid_id", "labels": [{"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_pet"}, {"name": "subSuite", "value": "TestGetPet"}, {"name": "host", "value": "4c2631702ffc"}, {"name": "thread", "value": "7-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_pet"}]}